//@version=4
// Created by @gu5tavo71 10/2019 for @Spongecoinbob
// Github repo https://github.com/gu5tavo/Tradingview
// Disclaimer: I am not a financial advisor
//             For purpose educate only
// If you have had a positive experience, you can buy me a beer ;)
// BTC: 1MbHMN63WnsFYEavsGK4nMWSUoEiuiScny
// Paypal: https://www.paypal.me/gu5tavo71
//////////////////////////////////////////////////////////////////
study(title="Heikin Ashi [Gu5]", shorttitle= "HA", overlay= true)
 
//Input
candlesCount = input(defval= 3, minval= 1, maxval= 5, title= "Candles Count")
 
//Setting
HAOpen = security(heikinashi(syminfo.tickerid), timeframe.period, open)
HAClose = security(heikinashi(syminfo.tickerid), timeframe.period, close)
HAHigh = security(heikinashi(syminfo.tickerid), timeframe.period, high)
HALow = security(heikinashi(syminfo.tickerid), timeframe.period, low)
 
HACandleup = HAClose > HAOpen
HACandledn = HAClose < HAOpen
 
HACandleupCount = 0
HACandleupCount := HACandledn[1] and HACandleup ? 1 :
	 HACandledn[2] and HACandleup [1] and HACandleup ? 2 :
	 HACandledn[3] and HACandleup [2] and HACandleup [1] and HACandleup ? 3 :
	 HACandledn[4] and HACandleup [3] and HACandleup [2] and HACandleup[1] and HACandleup ? 4 :
	 HACandledn[5] and HACandleup [4] and HACandleup [3] and HACandleup[2] and HACandleup[1] and HACandleup ? 5 :
	 HACandleupCount[1]
 
HACandlednCount = 0
HACandlednCount := HACandleup[1] and HACandledn ? 1 :
	 HACandleup[2] and HACandledn [1] and HACandledn ? 2 :
	 HACandleup[3] and HACandledn [2] and HACandledn [1] and HACandledn ? 3 :
	 HACandleup[4] and HACandledn [3] and HACandledn [2] and HACandledn[1] and HACandledn ? 4 :
	 HACandleup[5] and HACandledn [4] and HACandledn [3] and HACandledn[2] and HACandledn[1] and HACandledn ? 5 :
	 HACandlednCount[1]
 
exitShort = HACandleupCount == candlesCount and HACandleupCount[1] != candlesCount 
exitLong = HACandlednCount == candlesCount and HACandlednCount[1] != candlesCount
 
//Drawing Alert
Color10 = #006400//Green
Color20 = #8B0000//Red
Color30 = #ffffff//White
 
HALabelTex = exitShort ? "Exit\nShort":
	 exitLong ? "Exit\nLong": na
HALabelColor = exitShort ? Color20 :
	 exitLong ? Color10 : na
HALabelTexColor = Color30
HALabelStyle = HACandleup ? label.style_labelup : label.style_labeldown
HALabelyloc = HACandleup ? yloc.belowbar : yloc.abovebar
HALabel = label.new(bar_index, close,
	 text= HALabelTex,
	 color= HALabelColor,
	 textcolor= HALabelTexColor,
	 style= HALabelStyle,
	 yloc= HALabelyloc)
HALabelDel = exitShort or exitLong
label.delete(not HALabelDel ? HALabel: na)
 