//@version=4
// Created by @gu5tavo71 10/2019 for @ynchart 
// Github repo https://github.com/gu5tavo/Tradingview
// Disclaimer: I am not a financial advisor. 
//             For purpose educate only
// If you have had a positive experience, you can buy me a beer ;)
// BTC: 1MbHMN63WnsFYEavsGK4nMWSUoEiuiScny
// Paypal: https://www.paypal.me/gu5tavo71
///////////////////////////////////////////////////////////////
study(title= "Mix2: Stoch RSI + MACD [Gu5]", shorttitle= "Mix2", format= format.price, precision= 2, overlay= false)
 
//Input
src = input(title= "Source", type= input.source, defval= close)
//Input Stoch RSI
smoothK = input(3, minval= 1, title="Stoch %K")
smoothD = input(3, minval= 1, title="Stoch %D")
lengthRSI = input(14, minval= 1, title="Length RSI")
lengthStoch = input(14, minval= 1, title="Length Stoch")
 
//Input MACD
fast_length = input(title= "MACD Fast Length", type= input.integer, defval= 12)
slow_length = input(title= "MACD Slow Length", type= input.integer, defval= 26)
signal_length = input(title= "MACD Signal Smoothing", type= input.integer, minval = 1, maxval = 50, defval = 9)
sma_source = input(title= "MACD Oscillator", type= input.bool, defval= false)
sma_signal = input(title= "MACD Signal Line", type= input.bool, defval= false)
 
//Setting 
//Setting Stoch RSI
rsi1 = rsi(src, lengthRSI)
k = sma(stoch(rsi1, rsi1, rsi1, lengthStoch), smoothK)
d = sma(k, smoothD)
// Plot colors for MACD, but no drawing
// col_grow_above = #26A69A 
// col_grow_below = #FFCDD2 
// col_fall_above = #B2DFDB 
// col_fall_below = #EF5350 
// col_macd = #0094ff 
// col_signal = #ff6a00
// Calculating MACD 
fast_ma = sma_source ? sma(src, fast_length) : ema(src, fast_length)
slow_ma = sma_source ? sma(src, slow_length) : ema(src, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal ? sma(macd, signal_length) : ema(macd, signal_length)
hist = macd - signal
 
//Drawing
//Drawing Stoch RSI
kl = plot(k, color= color.blue)
plot(d, color= color.orange)
h0 = hline(80)
h1 = hline(20)
fill(h0, h1, color= na, transp= 80)
//No Drawing MACD
// plot(hist, title= "Histogram", style= plot.style_columns, color= (hist>=0 ? (hist[1] < hist ? col_grow_above : col_fall_above) : (hist[1] < hist ? col_grow_below : col_fall_below) ), transp= 0 )
// plot(macd, title= "MACD", color= col_macd, transp= 0)
// plot(signal, title= "Signal", color= col_signal, transp= 0)
 
//Setting Alert Signal
//Setting Alert Signal Stoch RSI
StoRSIup = k > 80 
StoRSIdn = k < 20 
colorStoRSIup = StoRSIup ? color.green: na
colorStoRSIdn = StoRSIdn ? color.red: na
//Setting Alert MACD
crossmacd = cross (macd, signal)
macdup = signal < 0
macddn = signal > 0
//Setting Alert MIX
buysignal = StoRSIup and crossmacd and macdup
sellsignal = StoRSIdn  and crossmacd and macddn
colorcrossmacd = buysignal? color.green:
	 sellsignal ? color.red:
	 crossmacd and macddn? color.orange:
	 crossmacd and macdup? color.orange:
	 na
 
//Drawing Alert Signal
//Drawing Alert Signal Stoch RSI
hline0 = plot(80, color= color.gray, linewidth= 1,title= "hline 0", style= plot.style_circles)
hline1 = plot(20, color= color.gray, linewidth= 1,title= "hline 1", style= plot.style_circles)
fill(kl, hline0, color= colorStoRSIup, transp= 50)
fill(kl, hline1, color= colorStoRSIdn, transp= 50)
//Drawing Alert MACD
fill(hline0, hline1, color= colorcrossmacd, transp= 50)
//Drawing Alert MIX
plotshape(buysignal, title= "buy", style= shape.labelup, location= location.bottom, color= color.green, transp= 0, text= "buy", textcolor= color.white, size= size.normal, transp= 50)
plotshape(sellsignal, title= "sell", style= shape.labeldown, location= location.top, color= color.red, transp= 0, text= "sell", textcolor= color.white, size= size.normal, transp= 50)
