//@version=4
// Created by @gu5tavo71 10/2019 for @Spongecoinbob
// Github repo https://github.com/gu5tavo/Tradingview
// Disclaimer: I am not a financial advisor
//             For purpose educate only
// If you have had a positive experience, you can buy me a beer ;)
// BTC: 1MbHMN63WnsFYEavsGK4nMWSUoEiuiScny
// Paypal: https://www.paypal.me/gu5tavo71
//////////////////////////////////////////////////////////////////
study(title="Heikin Ashi for @Spongecoinbob [Gu5]", shorttitle= "HA", overlay= true)
 
//Setting
HAOpen = security(heikinashi(syminfo.tickerid), timeframe.period, open)
HAClose = security(heikinashi(syminfo.tickerid), timeframe.period, close)
HAHigh = security(heikinashi(syminfo.tickerid), timeframe.period, high)
HALow = security(heikinashi(syminfo.tickerid), timeframe.period, low)
 
HACandleup = HAClose > HAOpen
HACandledn = HAClose < HAOpen
 
exitShort = HACandledn[3] and HACandleup [2] and HACandleup [1] and HACandleup
exitLong = HACandleup[3] and HACandledn [2] and HACandledn [1] and HACandledn
 
//Drawing Alert
plotshape(exitShort, title = "Exit Short", text ="Exit\nShort", 
	 textcolor = color.white,color = color.red, transp = 0, 
	 style= shape.labelup, size = size.normal, location= location.belowbar)
plotshape(exitLong, title = "Exit Long", text ="Exit\nLong",
	 textcolor = color.white, color = color.green, transp = 0,
	 style= shape.labeldown, size = size.normal, location= location.abovebar)