//@version=4
// Original Indicator: Weekly/Monthly Close by icostan
// Actual Study Version: @gu5tavo71  for @kidcuauh
// 
// Github repo https://github.com/gu5tavo/Tradingview
// Disclaimer: I am not a financial advisor. 
//             For purpose educate only
// If you have had a positive experience, you can buy me a beer ;)
// BTC: 1MbHMN63WnsFYEavsGK4nMWSUoEiuiScny
// Paypal: https://www.paypal.me/gu5tavo71
///////////////////////////////////////////////////////////////
study(title="Weekly Open [Gu5]", shorttitle= "Weekly Open", overlay= true)
 
// inputs
src = input(open, title= "Source")
 
//Setting
week_close = valuewhen(barstate.ishistory and not timeframe.ismonthly,
	 security(syminfo.tickerid, 'W', close), 0)
CrossWeek = week_close != week_close[1]
CrossWeekB = barssince(CrossWeek)
CrossWeekW = valuewhen(CrossWeek, src, 0)
CrossWeekColor = CrossWeek ? na : color.orange
 
//Drawing
plot(CrossWeekW, title= "Open Week", color= CrossWeekColor,
	 linewidth= 2, style= plot.style_line)
 